version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  visa-req:
    build:
      context: ./visa-req
    container_name: visa-req
    ports:
      - "3000:3000"
    depends_on:
      - mongo
   
  visa-admin:
    build:
      context: ./visa-admin
    container_name: visa-admin
    ports:
      - "4000:4000"
    depends_on:
      - mongo
 

volumes:
  mongo-data:
